export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';

export const CONVERT_CURRENCY = 'CONVERT_CURRENCY';

export const SELECT_PRODUCT = 'SELECT_PRODUCT';

export const SELECT_ALL = 'SELECT_ALL';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const DELETE_PRODUCT_SELECTED = 'DELETE_PRODUCT_SELECTED';
